In [1]:
import numpy as np
import numpy.random as rnd

In [32]:
def mult_matrices():
    print(f"Ingresa los elementos de una matriz 3x3")
    n = 1
    A = np.zeros([3,3], float)

    for i in range(3):
        for j in range(3):
            A[i][j] = float(input(f"Elemento {n}:"))
            n += 1

    B = rnd.random((3, 3))

    print(f"La matriz A es\n{A}")
    print(f"La matriz B generada aleatoriamente es\n{B}")
    print(f"El producto de las matrices es \n{A @ B}")
        
        

In [31]:
mult_matrices()

Ingresa los elementos de una matriz 3x3


Elemento 1: 1
Elemento 2: 1
Elemento 3: 1
Elemento 4: 1
Elemento 5: 1
Elemento 6: 1
Elemento 7: 1
Elemento 8: 1
Elemento 9: 1


La matriz A es
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
La matriz B generada aleatoriamente es
[[0.09252934 0.61679706 0.83736663]
 [0.86938754 0.50778616 0.15226052]
 [0.6217365  0.26450909 0.20421253]]
El producto de las matrices es 
[[1.58365338 1.38909231 1.19383968]
 [1.58365338 1.38909231 1.19383968]
 [1.58365338 1.38909231 1.19383968]]
